version: '3'
services:
  testserver:
    build:
      dockerfile: ./docker/server.dockerfile
      context: .
    image: mtrentz/testserver
    container_name: testserver
    volumes:
      - ./files:/app/files
    ports:
      - "8001:8001"
    networks:
      - net
      
  testclient:
    build:
      dockerfile: ./docker/client.dockerfile
      context: .
    image: mtrentz/testclient
    container_name: testclient
    volumes:
      - ./files:/app/files
    networks:
      - net
    depends_on:
      - "testserver"

networks:
  net:
    driver: bridge